# PRODUCTION DOCKER-COMPOSE
# Use this file for production deployments.
# It uses the .env file for environment variables.
#
# To run: make prod-up
# To stop: make prod-down
# To view logs: make prod-logs

services:
  # --- The Background Worker Service ---
  worker:
    build: ./worker
    container_name: sniper-worker
    volumes:
      - ./data:/app/data
    env_file:
      - ./.env        # Use production environment variables
    environment:
      - OTEL_EXPORTER_TYPE=JAEGER
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    restart: always

  # --- The API Service (Temporarily Disabled) ---
  # api:
  #   build: ./api
  #   container_name: sniper-api
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./data:/app/data
  #   env_file:
  #     - ./.env # Use production environment variables
  #   depends_on:
  #     - worker
  #   restart: always

  # --- Jaeger Tracing Service ---
  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
    restart: always