# The 'version' key has been removed as it's obsolete.

services:
  # --- The Sniper Bot Service ---
  bot:
    build: ./bot
    container_name: sniper-bot    # Added for easy reference (e.g., 'docker logs sniper-bot')
    volumes:
      - ./data:/app/data
    env_file:
      - ./.env
    restart: always

  # --- The API Service ---
  api:
    build: ./api
    container_name: sniper-api    # Added for easy reference
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    env_file:
      - ./.env
    depends_on:                   # Ensures the 'bot' service is created before the 'api'
      - bot
    restart: always