version: 1
disable_existing_loggers: false

formatters:
  detailed:
    format: '%(asctime)s - %(name)-22s - %(levelname)-8s - %(message)s'
  simple:
    format: '%(name)-22s - %(levelname)-8s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: sniper.log
    maxBytes: 10485760
    backupCount: 5
    encoding: utf8

loggers:
  __main__:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  
  get_magic_eden_data:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  get_alt_data:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  database:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  
  discord_bot:
    level: INFO
    handlers: [console, file]
    propagate: no

  tracing:
    level: INFO
    handlers: [console, file]
    propagate: no

root:
  level: WARNING
  handlers: [console, file]